open! Core

(* http://rosalind.info/problems/ba1a/ *)

(* Function to count the number of a's.  Not actually what the
   homework requires. *)
let pattern_count s pat = 
  let pat_length = String.length pat in
  let count = ref 0 in
  for i = 0 to String.length s - pat_length do
    if String.equal (String.sub s ~pos:i ~len:pat_length) pat then 
      count := !count + 1
   done;
    !count

let input = "AGTAGTGGTACATAGTGGTTAGTGGTACTAGTGGTATGTAGTGGTGAGCTATAGTGGTCCAGAAGCACTAGTGGTTGCTAGTGGTTATAGTGGTTAGTGGTGTAGTGGTGTTAACTAGTGGTTAGTGGTATAGTGGTTTAGTGGTGTAGTGGTGCGTAGTGGTAGTCCCTTAGTGGTCTAGTGGTTAGTGGTGTCATAGTGGTTAGTGGTCTTAGTGGTTAGTGGTCAATGTAGTGGTTAGTGGTTAGTGGTTGGAGATAGTGGTTAGTGGTCTAGTGGTAGATAGTGGTTAGTGGTTACTGAGGTCGTTAGTGGTGTTTAGTGGTTAGTGGTTAGTGGTATGGTAGTGGTGCCCGTAGTGGTTAGTGGTAGATAGTGGTCATAGTGGTGTCGAGTGTAGTGGTAGGTAGTGGTGCCATAGTGGTTCACGAGTAGTGGTGTAGTGGTCTAGTGGTGTTAGTGGTCCTAGTGGTATAGTGGTTTTTACATTGATAGTGGTATAGTGGTTATAGTGGTGACTTAGTGGTGTCTGTAGTGGTTAGTGGTTAGTGGTGTCGTAGTGGTAAGCGAGCTTAGTGGTCATGTAGTGGTTTAGTGGTGTAGTGGTTCAGATCAGTACTAGTGGTATATAGTGGTTAGTGGTAACGGTCAATAGTGGTTAGTGGTTCCATCTAGTGGTTGATAGTGGTCTAGTGGTCCATCGTAGTGGTGTAGTGGTATTAGTGGTAATAGTGGTCGTAGTGGTTAGTGGTGCCCTAGTGGTGATAGTGGTCTTTTTAGTGGTGATTTCTAGTGGTCAGTGATAGTGGTTAGTGGTAGTAGTGGTTAGTGGTATTGCCCATAGTGGTTGGGTAGTGGTTACCTGTAGTGGTTAGTGGTTAGAGTGTCTAGTGGTCGTAGTGGTGTAGTGGTTAGTGGTTAGTGGTGAATTTAGTGGTATAGTGGT"
let pattern = "TAGTGGTTA"

(* This is the test format we can use for trying things out and for
   doing computations.  Things that you print out will get captured in
   expect blocks. *)
let%expect_test "" =
  let test s pat = printf "%d\n" (pattern_count s pat) in
  test "AAABBAAAACTG" "AA";
  [%expect {| 5 |}];
  test input pattern;
  [%expect {| 28 |}]
;;
